### ISSUE TITLE
Migrate extension to the Camunda Community Hub

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/camunda-bpm-platform-osgi#71]
Hi Ronny,

I hope today finds you well! My name is Rin Oliver, and I'm a Technical Community Builder at Camunda. I'm opening this issue today to ask if you might be interested in migrating this extension over to the [Camunda Community Hub](https://github.com/camunda-community-hub/community)? 

We'd love to hear your feedback on how we might improve the overall community extension development process for maintainers and contributors moving forward, and learn more about what you'd like to see from this initiative in the future.

If migrating this extension something you'd be interested in, I can send you the instructions for doing so via email, or whatever communication method works best for you. If you are no longer able to maintain this extension, if it is migrated to the Hub I would be more than happy to add a [lifecycle badge](https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md#abandoned-) to it indicating that the project is in need of a new maintainer.

I'm also more than happy to schedule a call and talk over this in more detail if that would be preferable to you, for whenever best suits your schedule over the next few weeks. 

Thank you so much for your time. I look forward to hearing from you.

**Comment by rbraeunlich** [comment]
Hey @celanthe 
sorry for the late response. Sure, we can migrate the extension to the hub. I don't see any problems with that.
It would be great if somebody could take over the project. I don't have much time these days to care for it. I would be very sad if it was abandoned but I can't do much to keep it alive.

**Comment by celanthe** [comment]
Hi @rbraeunlich,

Thank you so much for getting back to me! I'll reach out to Dan to get your email address, and will follow up with you next week. I am more than happy to help you with getting the repo transferred over, and with highlighting that it's in search of a new maintainer.

I appreciate your time and your response, and look forward to circling back next week.

Best,
Rin

**Comment by celanthe** [comment]
Hi @rbraeunlich! I've gotten this extension migrated over to the Community Hub, so I'll close out this issue to avoid any confusion! :)
